"""
Helper configuration for all scrapers.
Contains the list of scraper modules to run.
"""

# List of scraper module names (without .py extension)
# Each scraper should be in the 'scrapers' directory
SCRAPERS = [
    # "knight_commercial",
    # "build_out",
    # "glanmor_property",
    # "glinsman_weller",
    # "goldenberg_real_estate", 
    # "gp_surveyors",
    # 'gregory_moore_property',
    # 'gryphon_property_partners',
    # 'gvproperty',
    # 'g_v_a',
    # "hants_realty",
    # 'harrocks_commercial_property',
    # 'hartnell_taylor_cook',
    # 'harvey_burns_co',
    # 'hayward_fox',
    # 'h_d_a_k',
    # 'heaney_micklethwaite',
    # 'heb_chartered_surveyors',
    # 'herron_associates',
    # 'h_m_c_surveyors',
    # 'hough_gould',
    # 'howse_associates',
    # 'hummerstone_hawkins',
    # 'hutchinson_morrison_childs',
    # 'hynes_illingworth',
    # 'h_r_h_retail',
    # 'ian_scott_international',
    # 'impey_company',
    # 'ingleby_trice',
    # 'j_h_walter',
    # 'j_r_b_t_commercial_property',
    # 'jaggard_macland',
    # 'jarroms',
    # 'jem_property',
    # 'jim_raw_rees',
    # 'john_whiteman_co',
    # 'johnson_tucker',
    # 'joiner_cummings',
    # 'justice_co',
    # 'kavanaghs',
    # 'kimmre',
    # 'l_b_l_real_estate',
    # 'leighton_goldhill'
    # 'leopold_farmer',
    # 'levy_real_estate',
    # 'lexicon_c_r_e',
    # 'lisney', csv remaining
    # 'lofthouse_and_partners',
    # 'london_clancy',
    # 'phil_reid_associates',
    # 'philip_marsh_collins_deung',
    # 'p_k_3_agency',
    # 'potter_associates',
    # 'advantage_investment',
    # 'property_sourcers_4_u',
    # 'rand_surveyors',
    # 'pudney_shuttleworth',
    # 'r_a_r_e',
    # 'rawstron_johnson',
    # 'reddin_clancy_co',
    # 'rees_denton',
    # 'p_s_k_knighton',
    # 'r_a_f_estates', csv remaining
    # 'reid_rose_gregory', csv remaining
    # 'ridley_thaw',
    # 'r_k_real_estate',
    # 'roger_etchells_co',
    # 'roger_hannah',
    # 'commercial_property_partners',
    # 'cordage_group',
    # 'cortex_partners',
    
    # 'cradick_retail',
    # 'crossland_otter_hunt'.
    # 'crow_watkin',
    # 'curson_sowerby_partners', csv remaining
    # 'cuthbert_white',
    # 'cyril_leonard',
    # 'dabora_conway',
    # 'dalkin_co',
    # 'daniel_hirst',
    # 'davis_coffer_lyons',
    # 'davison_blackett',
    # 'd_b_a_sdvisors',
    # 'd_c_care',
    # 'deriaz_campsie', csv remaining
    # 'd_l_p_surveyors',
    # 'drakesfield',
    # 'd_t_r_e', csv remaining
    # 'dunitz_co',
    # 'dunster_morton', csv remaining
    # 'durlings'
    # 'edgerley_simpson_howe',
    # 'elsom_spettigue_associates',
    # 'emanuel_oliver',
    # 'emberson_co',
    # 'e_m_r_property',
    # 'e_r_i_c_surveyors',
    # 'e_t_p_property',
    # 'everard_cole',
    # 'exigen_property',
    # 'e_y_c_o', #csv remaining and pagination check
    # 'fairhurst_buckley',
    # 'fawcett_mead',
    # 'fifield_glyn',
    # 'finch_commercial_real_estate',
    # 'first_city',
    # 'fleurets',
    # 'flude_property_consultants',
    # 'forge',
    # 'francis_darrah',
    'frazer_kidd_partners',

]

